name: Delete Merged or Closed Branches

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete merged or closed branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          # Check if branch matches the pattern update-content-dd-mm-yy-hh-mm-ss
          if [[ $BRANCH_NAME =~ ^update-content-[0-3][0-9]-[0-1][0-9]-[0-9]{2}-[0-2][0-9]-[0-5][0-9]-[0-5][0-9]$ ]]; then
            echo "Branch $BRANCH_NAME matches pattern, checking if it can be deleted..."
            
            # Check if branch is merged or PR is closed
            if [ "${{ github.event.pull_request.merged }}" = "true" ] || [ "${{ github.event.action }}" = "closed" ]; then
              echo "Deleting branch $BRANCH_NAME..."
              git push origin --delete $BRANCH_NAME
            else
              echo "Branch $BRANCH_NAME is not merged or closed, skipping deletion."
            fi
          else
            echo "Branch $BRANCH_NAME does not match pattern, skipping."
          fi
